# Explore chemical space generated by each representation

In [ ]:
from deepmol.compound_featurization import NPClassifierFP
from deepmol.loaders import CSVLoader

dataset = CSVLoader(dataset_path="../test_dataset.csv",
            smiles_field="SMILES").create_dataset()

In [13]:
import pandas as pd

test = pd.read_csv("../test_dataset.csv")
train = pd.read_csv("../train_dataset.csv")
valid = pd.read_csv("../validation_dataset.csv")

merged = pd.concat([train, valid, test], ignore_index=True)

In [14]:
# generate inchikeys
from rdkit import Chem
from rdkit.Chem import AllChem

merged['InChIKey'] = merged['SMILES'].apply(lambda x: Chem.MolToInchiKey(Chem.MolFromSmiles(x))[:14])

In [15]:
test = pd.read_csv("test_set_smiles.csv")
test.shape

(28429, 2)

In [16]:
test_without_duplicates = test.drop_duplicates(subset=['smiles'])
test_without_duplicates.shape

(11317, 2)

In [17]:
test_without_duplicates["InChIKey"] = test_without_duplicates['smiles'].apply(lambda x: Chem.MolToInchiKey(Chem.MolFromSmiles(x))[:14])

/tmp/ipykernel_2182985/100639764.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_without_duplicates["InChIKey"] = test_without_duplicates['smiles'].apply(lambda x: Chem.MolToInchiKey(Chem.MolFromSmiles(x))[:14])

In [18]:
merged[merged['InChIKey'].isin(test_without_duplicates['InChIKey'])]

,key,SMILES,Alkaloids,Amino acids and Peptides,Carbohydrates,Fatty acids,Polyketides,Shikimates and Phenylpropanoids,Terpenoids,Alkylresorsinols,...,Wax diesters,Wax monoesters,Xeniaphyllane diterpenoids,Xenicane diterpenoids,Yohimbine-like alkaloids,Zearalenones,Zizaane sesquiterpenoids,m-Terphenyls,p-Terphenyls,InChIKey
68,WSVWKHTVFGTTKJ,COc1cc2c3c(c1OC)-c1cc4c(cc1C[C@@H]3N(C)CC2)OCO4,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,WSVWKHTVFGTTKJ
70,JDMYIRPBIXAKJM,CCCCC/C=C\C/C=C\C/C=C\CCCCC(=O)OC[C@H](COP(=O)...,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,JDMYIRPBIXAKJM
407,HEURTYMJWQPWNN,COC1=CC(=O)OC(CCc2ccc(OC)c(OC)c2)C1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,HEURTYMJWQPWNN
423,WTOYNNBCKUYIKC,C=C(C)C1CCC2=CC(=O)CC(C)C2(C)C1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,WTOYNNBCKUYIKC
678,NTAYABHEVAQSJS,CCCCC[C@H](O)/C=C/[C@H]1[C@H]2C[C@H](OO2)[C@@H...,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NTAYABHEVAQSJS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179902,CZCOHVXNUPVUBC,COc1ccc(CCc2cc(OC)cc(=O)o2)cc1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,CZCOHVXNUPVUBC
179914,DFPMSGMNTNDNHN,CC1OC(OC2C(Oc3cc(O)c4c(c3)OC(c3ccc(O)cc3)CC4=O...,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,DFPMSGMNTNDNHN
180158,OVRNDRQMDRJTHS,CC(=O)NC1C(O)OC(CO)C(O)C1O,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,OVRNDRQMDRJTHS
180161,SRQSAJRUMDQMMS,CCCCC/C=C\C/C=C\C/C=C\C/C=C\CCCC(=O)O[C@H](COC...,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,SRQSAJRUMDQMMS
180266,BXLYSRPHVMCOPS,CCC(C)C(NC(=O)C(N)CO)C(=O)O,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,BXLYSRPHVMCOPS

In [2]:
from deepmol.compound_featurization import NPClassifierFP

dataset = NPClassifierFP().featurize(dataset)

NPClassifierFP: 100%|██████████| 15541/15541 [00:20<00:00, 749.65it/s]

In [3]:
dataset.get_shape()

2025-10-01 16:32:04,696 — INFO — Mols_shape: (15541,)
2025-10-01 16:32:04,697 — INFO — Features_shape: (15541, 6144)
2025-10-01 16:32:04,698 — INFO — Labels_shape: None

((15541,), (15541, 6144), None)

In [4]:
# create a tsne plot
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
X = dataset.X
tsne = TSNE(n_components=2, random_state=42)
X_embedded = tsne.fit_transform(X)

In [5]:
import pandas as pd

pandas_dataset = pd.read_csv("../test_dataset.csv")
pandas_dataset

,key,SMILES,Alkaloids,Amino acids and Peptides,Carbohydrates,Fatty acids,Polyketides,Shikimates and Phenylpropanoids,Terpenoids,Alkylresorsinols,...,Vitamin D3 and derivatives,Wax diesters,Wax monoesters,Xeniaphyllane diterpenoids,Xenicane diterpenoids,Yohimbine-like alkaloids,Zearalenones,Zizaane sesquiterpenoids,m-Terphenyls,p-Terphenyls
0,XFBQQSLGCORCGH,CCCCC/C=C\C/C=C\CCCCCCCC(=O)OC[C@@H](COC(=O)CC...,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,UBJDLKGJDZONCO,COc1cc(C2Oc3cc4c(cc3C2COC(C)=O)-c2c(cc(O)cc2OC...,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,WCXMGPNELNHROM,COc1cc2c(cc1O)OC(c1ccccc1)CC2=O,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,XRBNWTBBMTUZLA,COc1cccc(CCOC2OC(CO)C(OC(=O)C=Cc3ccc(O)c(O)c3)...,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,WDDXJPVDQFRGNC,CC(C)c1c(O)ccc2c1C(=O)CC1C(C)(C(=O)O)CCCC21C,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15536,COVDAEBDAVGGFK,CC(C)=CCC/C(C)=C/C/C=C(\C)[C@H](O)Cc1c[nH]c([N...,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15537,TXTGITRXQUOAJM,COC1Oc2ccccc2-c2c1oc1cc(O)c(C)c(O)c1c2=O,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
15538,VUAIYBIBQXIJKV,Cc1c2c(cc3c1CC(C)(C)C3=O)C(=O)OCC2,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15539,HFPLCFMATPQWMD,O=C(O)CC(Cl)Cl,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15540,GCEVIODPDGBRSE,CC(=O)OC1C2C(O)C(OC(=O)c3ccccc3)C3(C)C(OC(=O)c...,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# For each row, find columns with value 1 and assign their names to a new column 'Assigned_Class'
def get_assigned_classes(row):
    return [col for col in pandas_dataset.columns if row[col] == 1][0]

pandas_dataset['Assigned_Class'] = pandas_dataset.apply(get_assigned_classes, axis=1)
pandas_dataset['Assigned_Class']

0                            Fatty acids
1        Shikimates and Phenylpropanoids
2        Shikimates and Phenylpropanoids
3        Shikimates and Phenylpropanoids
4                             Terpenoids
                      ...
15536                         Terpenoids
15537    Shikimates and Phenylpropanoids
15538                         Terpenoids
15539                        Fatty acids
15540                         Terpenoids
Name: Assigned_Class, Length: 15541, dtype: object

In [20]:
import matplotlib.pyplot as plt
import numpy as np
from deepmol.loaders import CSVLoader
from sklearn.manifold import TSNE
import pandas as pd
import sklearn

def generate_tsne_with_featurizer(featurizer, name=None, method=sklearn.manifold.TSNE):

    if not name:
        name = featurizer.__class__.__name__

    dataset = CSVLoader(dataset_path="../test_dataset.csv",
                smiles_field="SMILES").create_dataset()

    dataset = featurizer.featurize(dataset)
    X = dataset.X

    tsne = method(n_components=2, random_state=42)
    X_embedded = tsne.fit_transform(X)

    pandas_dataset = pd.read_csv("../test_dataset.csv")

    def get_assigned_classes(row):
        return [col for col in pandas_dataset.columns if row[col] == 1][0]

    pandas_dataset['Assigned_Class'] = pandas_dataset.apply(get_assigned_classes, axis=1)

    opacity = 0.5
    colors = {
        'blue': [55, 126, 184],
        'orange': [255, 127, 0],
        'green': [77, 175, 74],
        'pink': [247, 129, 191],
        'brown': [166, 86, 40],
        'purple': [152, 78, 163],
        'gray': [153, 153, 153],
        'red': [228, 26, 28],
        'yellow': [222, 222, 0]
    }

    c_str = {k:f'rgba({v[0]},{v[1]},{v[2]},{opacity})'
            for (k, v) in colors.items()}

    unique_classes = pandas_dataset["Assigned_Class"].unique()

    print(unique_classes)

    colors_keys = list(c_str.keys())
    c_str = {
        cls: colors_keys[i]
        for i, cls in enumerate(unique_classes)
    }

    # Create a figure for the t-SNE plot
    plt.figure(figsize=(10, 8))

    for cls in unique_classes:
        mask = pandas_dataset['Assigned_Class'] == cls
        plt.scatter(X_embedded[mask, 0], X_embedded[mask, 1], color=c_str[cls], label=cls, s=5)

    plt.title(f'{method.__name__} plot of {name} features')
    plt.clim(-0.5, len(unique_classes) - 0.5)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.xlabel(f'{method.__name__}_Component 1')
    plt.ylabel(f'{method.__name__}_Component 2')

    plt.savefig(f"{method.__name__}_plot_{name}.png", bbox_inches='tight', dpi=300,transparent=True)
    plt.close()

    # Create a separate figure for the legend
    plt.figure(figsize=(10, 0.5))
    plt.figlegend(handles=[plt.Line2D([0], [0], marker='o', color='w', label=cls, markerfacecolor=c_str[cls], markersize=7) for cls in unique_classes],
                 loc='center', ncol=1, title="Assigned Pathway")

    plt.savefig(f"{method.__name__}_legend_{name}.png", bbox_inches='tight', dpi=300, transparent=True)
    plt.close()

In [21]:
from deepmol.compound_featurization import NPClassifierFP

featurizer = NPClassifierFP()
# generate_tsne_with_featurizer(featurizer)
generate_tsne_with_featurizer(featurizer, method=sklearn.decomposition.PCA)

NPClassifierFP: 100%|██████████| 15541/15541 [00:23<00:00, 651.53it/s]

['Fatty acids' 'Shikimates and Phenylpropanoids' 'Terpenoids'
 'Polyketides' 'Alkaloids' 'Carbohydrates' 'Amino acids and Peptides']

In [16]:
from deepmol.compound_featurization import NeuralNPFP

featurizer = NeuralNPFP()
# generate_tsne_with_featurizer(featurizer, "NP_AUX")
generate_tsne_with_featurizer(featurizer, "NP_AUX", method=sklearn.decomposition.PCA)

NeuralNPFP: 100%|██████████| 15541/15541 [00:54<00:00, 282.85it/s]

In [17]:
from deepmol.compound_featurization import BiosynfoniKeys

featurizer = BiosynfoniKeys()
generate_tsne_with_featurizer(featurizer, "Biosynfoni", method=sklearn.decomposition.PCA)

BiosynfoniKeys: 100%|██████████| 15541/15541 [00:20<00:00, 752.66it/s]

In [18]:
import os
from deepmol.compound_featurization import LLM
from transformers import BertConfig, BertModel

from deepmol.standardizer import ChEMBLStandardizer

from deepmol.tokenizers import NPBERTTokenizer

transformer = LLM(model_path="../../NPBERT", model=BertModel, config_class=BertConfig,
                          tokenizer=NPBERTTokenizer(vocab_file=os.path.join("../../NPBERT", "vocab.txt")), device="cuda:0")

generate_tsne_with_featurizer(transformer, "NPBERT", method=sklearn.decomposition.PCA)

Some weights of BertModel were not initialized from the model checkpoint at ../../NPBERT/model.pt and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
100%|██████████| 15541/15541 [01:38<00:00, 157.67it/s]

In [19]:
import os
from deepmol.compound_featurization import LLM

from deepmol.compound_featurization import LLM
from transformers import ModernBertModel, ModernBertConfig

transformer = LLM(model_path="../../ModernBERT", model=ModernBertModel, config_class=ModernBertConfig, device="cuda:1")

generate_tsne_with_featurizer(transformer, name="ModernBERT", method=sklearn.decomposition.PCA)

100%|██████████| 15541/15541 [09:39<00:00, 26.81it/s]